inherit_from:
  - https://raw.githubusercontent.com/ractor-tools/rubocop-ractor-tools/master/.rubocop.yml

Style/GlobalVars:
  Enabled: false

Metrics/MethodLength:
  Max: 16

Style/RescueModifier:
  Exclude:
    - 'spec/**/*.rb'
